name: MLOpsProject
channels:
  - apple
  - anaconda
  - conda-forge

dependencies:
  - python=3.9
  - scikit-learn
  - IPython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pillow
  - opencv
  - pip
  - requests
  - seaborn
  - spacy
  - statsmodels
  - progressbar2
  - setuptools
  - tensorflow-deps
  - python-dotenv
 
  - pip:
    - configparser
    - flatbuffers
    - flickrapi==3.0.dev0
    - pydot
    - selenium
    - webdriver-manager
    - tensorflow_hub
    - tensorflow-estimator
    - tensorflow-macos
    - tensorflow-metal