---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get timestamp for docker tag"
      shell: "(date +%Y%m%d%H%M%S)"
      register: tag
    - name: Print tag
      debug:
        var: tag
    - name: Build api-service container image
      community.general.docker_image:
        build:
          path: /psp-api-service
        name: gcr.io/{{ gcp_project }}/psp-app-api-service:{{ tag.stdout}}
        source: build
    - name: Push api-service image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/psp-app-api-service:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/psp-app-api-service:{{ tag.stdout}}
        push: yes
        source: local
    - name: Build frontend container image
      community.general.docker_image:
        build:
          path: /frontend-react
        name: gcr.io/{{ gcp_project }}/mushroom-app-frontend-react:{{ tag.stdout}}
        source: build
    - name: Push frontend image to GCR
      community.general.docker_image:
        name: gcr.io/{{ gcp_project }}/mushroom-app-frontend-react:{{ tag.stdout}}
        repository: gcr.io/{{ gcp_project }}/mushroom-app-frontend-react:{{ tag.stdout}}
        push: yes
        source: local
    - name: "Save docker tag"
      shell: echo {{ tag.stdout}} > .docker-tag
    - name: "Remove all unused containers"
      shell: docker system prune -a
